#!/bin/bash
# collect_indices.sh
# Fetches historical data for SPY + QQQ + DJIA constituents in batches

BIN="../bin/sr-cli -v"
BATCH_SIZE=18          # safe size - adjust if you want bigger/smaller batches

# ==================== SYMBOL LISTS ====================

# SPY - S&P 500 (as of latest data)
SPY_SYMBOLS=(
  NVDA AAPL MSFT AMZN GOOGL GOOG AVGO TSLA META BRK.B WMT LLY MU JPM AMD XOM V INTC JNJ ORCL
  CSCO COST CAT LRCX CVX ABBV NFLX BAC UNH KO AMAT PG PLTR MS GE HD MRK PM GS TXN GEV QCOM KLAC
  LIN IBM RTX WFC SNDK C AXP PANW TMUS PEP VZ MCD ANET ADI DELL NEE AMGN STX DIS T TJX BA CRWD
  GLW WDC GILD TMO BLK APH APP UNP SCHW ISRG WELL ABT ETN PFE CRM COP UBER BX HON DE PLD CB VRT
  BKNG SPGI MO LMT DHR BMY SYK LOW CVS SBUX COF PGR NEM VRTX ACN PH PWR SO EQIX CEG NOW CME CDNS
  HWM MDT SNPS TT ADBE FTNT DUK MAR WMB BNY FDX GD MCK ADP CMCSA FCX INTU CMI PNC WM HCA ICE BSX
  UPS ELV AMT SLB USB MNST CSX KKR JCI CIEN NXPI MMM MDLZ DDOG MRSH NOC ABNB MCO MPWR EMR SHW ORLY
  CI ROST EOG KMI MPC APO COHR LITE VLO HLT ITW CL AEP ECL PSX GM NSC DASH AON CTAS RCL TDG WBD
  DLR MSI CRH REGN HOOD SPG NKE BKR TRV APD FIX RSG SRE TFC AFL D F TRGP OKE TEL KEYS GWW URI OXY
  LHX O PCAR TGT FANG AZO TER ALL DVN MET PSA COR CTVA NUE VST AJG CARR NDAQ ETR AME EBAY ADSK MCHP
  XEL FAST EA ROK DAL HPE EW CVNA COIN EXC CAH GRMN ON FITB IDXX ODFL WAB VTR MSCI YUM STT CMG TTWO
  KR AIG DHI BDX AMP XYZ ED CCI PEG KDP HSY PYPL LYV JBL CBRE EME IRM CBOE ADM HIG HUM WEC SYY PCG
  IBKR EQT PRU SATS CCL PAYX HAL STLD ZTS VMC KVUE ACGL WAT ROP KMB Q LVS CPRT A UAL HBAN MLM WDAY
  EL MTB AXON NTRS AEE VICI CASY FISV EXR DTE RMD ATO RJF GEHC CNC NRG FICO TDY BIIB DOV VRSN KHC
  ARES IQV CNP TPR OTIS DXCM IR TPL FSLR NTAP EIX PPL FE CFG ES XYL VEEV CINF DOW AVB EXPE STZ ROL
  WRB HUBB CTSH EQR AWK JBHT WTW SYF PPG RF EXE BG KEY DRI DG HPQ CMS NI TSN CHD CPAY WSM FIS LYB
  RL ULTA PFG VRSK L WST MTD FFIV PHM TROW LEN SBAC DGX AKAM SMCI OMC VLTO LH STE EXPD CHRW ALB GPN
  LUV SW DD BRO EFX INCY VTRS EVRG PKG IFF LNT SNA CF MRNA DLTR FTV GIS CHTR ESS AMCR BR INVH PTC WY
  LII TSCO IP ZBH NVR KIM NDSN BEN TXT GNRC LDOS IEX HST MAA LULU DECK BALL GEN REG TKO CDW EG CSGP
  APA DOC MAS J GPC SOLV TRMB BBY TYL MKC FOXA DVA HII FOX AIZ PNW HAS SWKS UDR AVY COO ZBRA APTV GL
  PNR BF.B IVZ GDDY SWK ERIE ALGN PSKY HRL CLX ALLE SJM RVTY PODD IT CPT DPZ TTD AES FRT WYNN JKHY
  BAX MGM BXP UHS NWSA HSIC FDS ARE TAP BLDR AOS CRL TECH NCLH MOS POOL CAG CPB NWS EPAM
)

# QQQ - Nasdaq-100
QQQ_SYMBOLS=(
  NVDA AAPL MSFT AMZN GOOGL GOOG AVGO TSLA META WMT MU AMD ASML INTC CSCO COST LRCX NFLX AMAT PLTR
  ARM TXN QCOM KLAC LIN SNDK PANW TMUS PEP ADI AMGN STX MRVL CRWD WDC GILD APP ISRG HON PDD SHOP
  BKNG SBUX VRTX CEG CDNS SNPS ADBE FTNT MAR ADP CMCSA INTU MNST CSX MELI NXPI MDLZ DDOG ABNB MPWR
  ORLY ROST LITE AEP DASH CTAS WBD REGN BKR PCAR FANG MSTR ADSK XEL MCHP FAST EA FER EXC IDXX ODFL
  TTWO CCEP ALNY KDP PYPL TRI PAYX ROP CPRT WDAY AXON ZS GEHC KHC DXCM CTSH INSM VRSK CHTR
)

# DJIA - Dow 30
DJIA_SYMBOLS=(
  GS CAT MSFT UNH AMGN V HD AXP SHW AAPL TRV JPM MCD AMZN IBM JNJ HON BA NVDA CVX CRM MMM PG MRK
  CSCO WMT DIS KO VZ NKE
)

# Combine all unique symbols (removes duplicates automatically)
ALL_SYMBOLS=("${SPY_SYMBOLS[@]}" "${QQQ_SYMBOLS[@]}" "${DJIA_SYMBOLS[@]}")
ALL_SYMBOLS=($(printf '%s\n' "${ALL_SYMBOLS[@]}" | sort -u))

echo "=== Collecting historical data for ${#ALL_SYMBOLS[@]} symbols (SPY + QQQ + DJIA) ==="

# Process in batches
batch=()
for sym in "${ALL_SYMBOLS[@]}"; do
  batch+=("$sym")

  if [ ${#batch[@]} -eq $BATCH_SIZE ] || [ "$sym" = "${ALL_SYMBOLS[-1]}" ]; then
    symbols=$(IFS=,; echo "${batch[*]}")
    echo "→ Collecting batch of ${#batch[@]} symbols: $symbols"
    $BIN collect "$symbols"
    batch=()
    # optional: sleep 1   # be gentle on Yahoo if you want
  fi
done

echo "=== All collections finished! ==="